/** Booking domain constants — single source of truth */

const BOOKING_VEHICLE_TYPE = 'CAR';

const BOOKING_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
  NO_SHOW: 'NO_SHOW'
};

const PAYMENT_STATUS = {
  UNPAID: 'UNPAID',
  PAID: 'PAID',
  REFUND_PENDING: 'REFUND_PENDING',
  REFUNDED: 'REFUNDED'
};

const REFUND_STATUS = {
  NONE: 'NONE',
  PENDING: 'PENDING',
  PROCESSED: 'PROCESSED'
};

const CANCELLED_BY = {
  PASSENGER: 'PASSENGER',
  DRIVER: 'DRIVER',
  SYSTEM: 'SYSTEM'
};

const NOTIFICATION_TYPES = {
  BOOKING_REQUESTED: 'BOOKING_REQUESTED',
  BOOKING_CONFIRMED: 'BOOKING_CONFIRMED',
  BOOKING_REJECTED: 'BOOKING_REJECTED',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',
  REFUND_PREPARED: 'REFUND_PREPARED',
  RIDE_COMPLETED: 'RIDE_COMPLETED',
  SEATS_UPDATED: 'SEATS_UPDATED',
  RIDE_REQUEST_NEW: 'RIDE_REQUEST_NEW',
  RIDE_REQUEST_FARE_OFFER: 'RIDE_REQUEST_FARE_OFFER',
  RIDE_REQUEST_MATCHED: 'RIDE_REQUEST_MATCHED',
  RIDE_REQUEST_CHAT: 'RIDE_REQUEST_CHAT'
};

/** Active bookings block duplicate requests */
const ACTIVE_BOOKING_STATUSES = [
  BOOKING_STATUS.PENDING,
  BOOKING_STATUS.CONFIRMED
];

/** Seats count toward capacity */
const SEAT_HOLDING_STATUSES = [BOOKING_STATUS.CONFIRMED];

const PENDING_TTL_HOURS = 48;

const MAX_SEATS_PER_BOOKING = 4;

const BOOKING_MODES = {
  CARPOOL: 'CARPOOL',
  SOLO: 'SOLO'
};

module.exports = {
  BOOKING_VEHICLE_TYPE,
  BOOKING_STATUS,
  PAYMENT_STATUS,
  REFUND_STATUS,
  CANCELLED_BY,
  NOTIFICATION_TYPES,
  ACTIVE_BOOKING_STATUSES,
  SEAT_HOLDING_STATUSES,
  PENDING_TTL_HOURS,
  MAX_SEATS_PER_BOOKING,
  BOOKING_MODES
};
