const RIDE_REQUEST_STATUS = {
  SEARCHING: 'SEARCHING',
  OFFERS_PENDING: 'OFFERS_PENDING',
  ACCEPTED: 'ACCEPTED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED'
};

const RIDE_PHASE = {
  MATCHED: 'MATCHED',
  EN_ROUTE: 'EN_ROUTE',
  AT_PICKUP: 'AT_PICKUP',
  WAITING_PASSENGER: 'WAITING_PASSENGER',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED'
};

const OFFER_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  COUNTERED: 'COUNTERED',
  PASSENGER_ACCEPTED: 'PASSENGER_ACCEPTED',
  PASSENGER_REJECTED: 'PASSENGER_REJECTED',
  EXPIRED: 'EXPIRED'
};

const REQUEST_TTL_MINUTES = 15;
const SEARCH_AUTO_CANCEL_MINUTES = 5;
const OFFER_VISIBLE_SECONDS = 15;
const PICKUP_WAIT_MINUTES = 5;
const AT_PICKUP_RADIUS_METERS = 80;

module.exports = {
  RIDE_REQUEST_STATUS,
  RIDE_PHASE,
  OFFER_STATUS,
  REQUEST_TTL_MINUTES,
  SEARCH_AUTO_CANCEL_MINUTES,
  OFFER_VISIBLE_SECONDS,
  PICKUP_WAIT_MINUTES,
  AT_PICKUP_RADIUS_METERS
};
