export const endpoints = {
  login: '/admin/auth/login',
  me: '/admin/auth/me',
  logout: '/admin/auth/logout',
  overview: '/admin/dashboard/overview',
  activity: '/admin/dashboard/activity',
  charts: '/admin/dashboard/charts',
  users: '/admin/users',
  user: (id) => `/admin/users/${id}`,
  userStatus: (id) => `/admin/users/${id}/status`,
  userVerify: (id) => `/admin/users/${id}/verify`,
  userReviewDocuments: (id) => `/admin/users/${id}/review-documents`,
  userDocumentReview: (userId, documentType) => `/admin/users/${userId}/documents/${documentType}/review`,
  userDocumentsNotify: (id) => `/admin/users/${id}/documents/notify`,
  userWarn: (id) => `/admin/users/${id}/warn`,
  drivers: '/admin/drivers',
  approveDriver: (id) => `/admin/drivers/${id}/approve`,
  rejectDriver: (id) => `/admin/drivers/${id}/reject`,
  vehicles: '/admin/vehicles',
  vehicle: (id) => `/admin/vehicles/${id}`,
  vehicleReview: (id) => `/admin/vehicles/${id}/review`,
  verificationUsers: '/admin/verifications/users',
  verifications: '/admin/verifications',
  verificationReview: (id) => `/admin/verifications/${id}/review`,
  rideRequests: '/admin/ride-requests',
  rides: '/admin/rides',
  ride: (id) => `/admin/rides/${id}`,
  cancelRide: (id) => `/admin/rides/${id}/cancel`,
  bookings: '/admin/bookings',
  cancelBooking: (id) => `/admin/bookings/${id}/cancel`,
  refundBooking: (id) => `/admin/bookings/${id}/refund/prepare`,
  reports: '/admin/reports',
  resolveReport: (id) => `/admin/reports/${id}/resolve`,
  analytics: '/admin/analytics',
  realtime: '/admin/realtime/snapshot',
  announce: '/admin/notifications/announce'
};
